edition = "2018"
newline_style = "Unix"

# Unstable features are only available in nightly channel
format_strings = true
imports_granularity = "Item"
imports_layout = "HorizontalVertical"
trailing_comma = "Never"
