import argparse
import os
from pathlib import Path
from typing import Any, Optional, Union, final

_Arguments = Optional[list[str]]
_StrPath = Union[str, os.PathLike[str]]

EXTENSION: str = ...

@final
class SingleLineArgumentParser(argparse.ArgumentParser):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def convert_arg_line_to_args(self, arg_line: str) -> list[str]: ...

class ReplayException(Exception): ...
class OverwriteException(Exception): ...

def unpack(input: Path, output: Path) -> int: ...
def process(filename: _StrPath, overwrite: bool = ...) -> None: ...

def error(
    exception: Exception, /, quit: bool = ..., *, caller_frame: bool = ...
) -> None: ...
def main(argv: _Arguments = ...) -> int: ...
