import argparse
from pathlib import Path
from typing import Any, NoReturn, Optional, final

_Arguments = Optional[list[str]]

EXTENSION: str = ...


@final
class SingleLineArgumentParser(argparse.ArgumentParser):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def convert_arg_line_to_args(self, arg_line: str) -> list[str]: ...


class ReplayException(Exception): ...
class OverwriteException(Exception): ...


def unpack(input: Path, output: Path) -> int: ...
def process(path: Path, overwrite: bool = ...) -> None: ...


def error(exception: Exception) -> NoReturn: ...
def main(args: _Arguments = ...) -> None: ...
